### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [6]:
import numpy as np
vector = np.random.rand(10)
matrix = np.array([[11, 14, 17], [20, 23, 26], [29, 32, 35]])
print(vector)
print(matrix)
print(vector.shape)
print(matrix.shape)

[0.84570884 0.30127252 0.49454729 0.14217312 0.79667766 0.23002366
 0.39498858 0.94060834 0.33771425 0.42414393]
[[11 14 17]
 [20 23 26]
 [29 32 35]]
(10,)
(3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [9]:
#1
np.round(vector * 10, 2)

array([8.46, 3.01, 4.95, 1.42, 7.97, 2.3 , 3.95, 9.41, 3.38, 4.24])

In [10]:
#2
matrix * 2

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [11]:
#3
vector ** 2

array([0.71522343, 0.09076513, 0.24457702, 0.0202132 , 0.63469529,
       0.05291088, 0.15601598, 0.88474405, 0.11405092, 0.17989808])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [13]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [16]:
#1
result_matrix = np.dot(B, A)
print(result_matrix)

[[0.7281 0.5202]
 [0.2034 0.2846]]


In [19]:
#2
np.dot(result_matrix, C)

array([[0.5202],
       [0.2846]])

In [22]:
#3
np.dot(result_matrix, D)

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [23]:
#1
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [26]:
#2
vector.T.shape
#зміни розмірності не відбудеться

(10,)

In [30]:
#3
column_vector = np.expand_dims(vector, axis=1)
print(column_vector)
print(vector)

[[0.84570884]
 [0.30127252]
 [0.49454729]
 [0.14217312]
 [0.79667766]
 [0.23002366]
 [0.39498858]
 [0.94060834]
 [0.33771425]
 [0.42414393]]
[0.84570884 0.30127252 0.49454729 0.14217312 0.79667766 0.23002366
 0.39498858 0.94060834 0.33771425 0.42414393]


Ф-ція np.expand_dims таки змінила вектор рядок на вектор стовбчик

In [31]:
#4
print(column_vector.T)
print(column_vector.T.shape)

[[0.84570884 0.30127252 0.49454729 0.14217312 0.79667766 0.23002366
  0.39498858 0.94060834 0.33771425 0.42414393]]
(1, 10)
