В цьому домашньому завданні ми реалізуємо логістичну регресію на `numpy`.
Ці завдання допоможуть вам ґрунтовно засвоїти основні концепції логістичної регресії та реалізувати їх на практиці 🔥

#### Завдання 1: Реалізація функції сигмоїди
1. З використанням `numpy` напишіть функцію `sigmoid(z)` для обчислення значення сигмоїди згідно з формулою:
   $$
   \sigma(z) = \frac{1}{1 + e^{-z}}
   $$
2. Використовуючи цю функцію, обчисліть значення сигмоїди для наступних даних: $ z = [-2, -1, 0, 1, 2] $. Виведіть результат обчислень.


In [1]:
import numpy as np

In [2]:
#1.1
def sigmoid(z):
    import numpy as np 
    #внутрішній виклик бібліотеки щоб функція працювала якщо зовні біліотека не викликана
    z = np.array(z)
    return(1.0 / (1.0 + np.exp(-z)))

In [3]:
#тесуємо межі вхідних параметрів функції
print('число')
z = 1
print(sigmoid(z))

print('список')
z = [1, 1]
print(sigmoid(z))

print('np.array')
z = np.array(z)
print(sigmoid(z))

print('рядок')
z = '1'
print(sigmoid(z))

число
0.7310585786300049
список
[0.73105858 0.73105858]
np.array
[0.73105858 0.73105858]
рядок


UFuncTypeError: ufunc 'negative' did not contain a loop with signature matching types <class 'numpy.dtype[str_]'> -> None

Поведінка очікувана. Число і список рахуються, рядок ні.

In [4]:
#1.2
z = [-2, -1, 0, 1, 2]
sigmoid(z)

array([0.11920292, 0.26894142, 0.5       , 0.73105858, 0.88079708])



#### Завдання 2: Реалізація функції гіпотези для логістичної регресії
1. Напишіть функцію `hypothesis(theta, X)`, яка обчислює гіпотезу для логістичної регресії, використовуючи функцію сигмоїди. Формула гіпотези:
   $$
   h_\theta(x) = \sigma(\theta^T x) = \frac{1}{1 + e^{-\theta^T x}}
   $$
2. Використайте функцію `hypothesis` для обчислення значень гіпотези для наступних даних:
   
   $\theta = [0.5, -0.5]$
   
   $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  Виведіть результат обчислень.


In [5]:
#2.1
def hypothesis(theta, X):
    import numpy
    theta = np.array(theta)
    X = np.array(X)    
    z = np.dot(X, theta)
    return(sigmoid(z))

In [6]:
#2.2
theta = np.array([0.5, 0.5])
X = np.array([[1.0, 2.0], 
              [1.0, -1.0], 
              [1.0, 0.0],
              [1.0, 1.0]])
print(hypothesis(theta, X))

[0.81757448 0.5        0.62245933 0.73105858]


#### Завдання 3: Реалізація функції для підрахунку градієнтів фукнції втрат
1. Напишіть функцію `compute_gradient(theta, X, y)`, яка обчислює градієнти функції втрат для логістичної регресії. Формула для обчислення градієнта:
   $$
   \frac{\partial L(\theta)}{\partial \theta_j} = \frac{1}{m} \sum_{i=1}^{m} \left[ (h_\theta(x^{(i)}) - y^{(i)}) x_j^{(i)} \right]
   $$
2. Використайте функцію `compute_gradient` для обчислення градієнтів для наступних даних:

  $\theta = [0.5, -0.5]$

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Виведіть результат обчислень.

In [7]:
#3.1
def compute_gradient(theta, X, y):
    import numpy as np
    theta = np.array(theta)
    X = np.array(X)
    return(np.dot((hypothesis(theta, X) - y).T, X) / len(y))

In [8]:
#3.2
theta = np.array([0.5, 0.5])
X = np.array([[1.0, 2.0], 
              [1.0, -1.0], 
              [1.0, 0.0],
              [1.0, 1.0]])
y = np.array([1.0, 0.0, 1.0, 0.0])
compute_gradient(theta, X, y)

array([ 0.1677731 , -0.03344812])


#### Завдання 4: Реалізація повного батч градієнтного спуску

**Задача:**
1. Напишіть функцію `full_batch_gradient_descent(X, y, lr=0.1, epochs=100)`, яка реалізує алгоритм Full градієнтного спуску для логістичної регресії. Використовуйте такі формули:
   - Гіпотеза: $ h_\theta(x) = \sigma(\theta^T x) $
   - Оновлення параметрів: $ \theta_j := \theta_j - \alpha \frac{\partial L(\theta)}{\partial \theta_j} $
2. Використайте функцію `full_batch_gradient_descent` для обчислення параметрів моделі на наступних даних:

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Увага! Матриця $X$ вже має стовпець одиниць і передбачається, що це. - стовпець для intercept - параметра зсуву.

  Виведіть результат обчислень.


In [9]:
def full_batch_gradient_descent(X, y, lr=0.1, epochs=100):
    import numpy as np
    X = np.array(X)
    y = np.array(y)
    
    N = X.shape[1]
    theta = np.random.rand(N) 
    for _ in range(epochs):
        theta = theta + lr * compute_gradient(theta, X, y)
    return(theta)

In [10]:
X = np.array([[1.0, 2.0], 
              [1.0, -1.0], 
              [1.0, 0.0],
              [1.0, 1.0]])
y = np.array([1.0, 0.0, 1.0, 0.0])
theta = full_batch_gradient_descent(X, y, lr=0.1, epochs=100)
theta

array([4.84997654, 1.28093913])

#### Завдання 5. Обчислення точності моделі

1. Напишіть функцію `predict_proba(theta, X)`, яка використовує знайдені параметри $\theta$ для обчислення ймовірностей належності поточного прикладу з даних до класу $y=1$ на основі значень $\sigma(\theta^T x)$.

2. Напишіть функцію `predict(theta, X, threshold=0.5)`, яка обчислює клас з передбаченої імовірності належності екземпляра до класу 1 з порогом 0.5. Тобто якщо ймовірність менше 0.5, то передбачаємо клас 0, інакше клас 1.

3. Напишіть функцію `accuracy(y_true, y_pred)`, яка обчислює точність моделі, визначивши частку правильно передбачених класів.

  Формула метрики Accuracy:
  $$
  \text{Accuracy} = \frac{\sum_{i=1}^{m} I(\hat{{y}^{(i)}} = y^{(i)})}{m}
  $$

  де $\hat{{y}^{(i)}}$ - передбачене значення класу, $I$ - індикаторна функція (яка дорівнює 1, якщо умова виконується, і 0 - якщо ні), $m$ - кількість прикладів.

4. Обчисліть з використанням даних в завданні 4 $X$, $y$ та обчислених коефіцієнтах $\theta$ та виведіть на екран:
  - передбачені моделлю імовірності належності кожного з екземплярів в матриці `X` до класу 1
  - класи кожного екземпляра з матриці `X`
  - точність моделі.

In [24]:
def predict_proba(theta, X):
    return(hypothesis(theta, X))

def predict(theta, X, threshold=0.5):
    y_pred = predict_proba(theta, X)
    return((y_pred >= threshold).astype(int))
    #return(map(lambda x: 1 if x >= threshold else 0, y_pred))
    #Друге повернення це реалізація повернення відкладеної функції яка не виконається, 
    #доки не знадобляться значення
    #Часто використовується щоб не займати оперативну пам'ять
    
def accuracy(y_true, y_pred):
    import numpy as np
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    if len(y_true) == len(y_pred):
        return((y_true == y_pred).astype(int).sum() / len(y_true))

In [27]:
X = np.array([[1.0, 2.0], 
              [1.0, -1.0], 
              [1.0, 0.0],
              [1.0, 1.0]])
y = np.array([1.0, 0.0, 1.0, 0.0])
theta = full_batch_gradient_descent(X, y, lr=0.1, epochs=100)

print('Predict probability vector ', predict_proba(theta, X))
y_pred = predict(theta, X, threshold=0.5)
print('Predict clasification vector ', y_pred)
print('Accuracy ', accuracy(y, y_pred))

Predict probability vector  [0.99882867 0.87039084 0.97122618 0.99414023]
Predict clasification vector  [1 1 1 1]
Accuracy  0.5
